Repository vmware/cluster-api-upgrade-tool, pull requests merged in 2019-06, with the labels that each got.

#6 Cleanup
  main.go
  pkg/upgrade/config.go
  pkg/upgrade/control_plane.go
  pkg/upgrade/machine_deployment.go
  vendor/k8s.io/kubernetes/.bazelrc
  vendor/k8s.io/kubernetes/.kazelcfg.json
  vendor/k8s.io/kubernetes/BUILD.bazel
  vendor/k8s.io/kubernetes/Makefile
  vendor/k8s.io/kubernetes/Makefile.generated_files
  vendor/k8s.io/kubernetes/WORKSPACE
  vendor/k8s.io/kubernetes/cluster/gce/cos
  vendor/k8s.io/kubernetes/cluster/gce/custom
  vendor/k8s.io/kubernetes/cluster/gce/ubuntu
  vendor/k8s.io/kubernetes/cluster/juju/layers/kubernetes-master/actions/namespace-delete
  vendor/k8s.io/kubernetes/cluster/juju/layers/kubernetes-master/actions/namespace-list
Labels: cla-not-required

#17 Eliminate global logging
  Gopkg.lock
  Gopkg.toml
  main.go
  pkg/logging/logrus_logr.go
  pkg/upgrade/base.go
  pkg/upgrade/control_plane.go
  pkg/upgrade/key_pair.go
  pkg/upgrade/machine_deployment.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
Labels: enhancement, p2

#19 Eliminate etcdctl copy pasta
  pkg/internal/kubernetes/pod_exec.go
  pkg/upgrade/control_plane.go
Labels: cla-not-required

#21 Refactor validations
  main.go
  pkg/upgrade/config.go
Labels: cla-not-required

#23 Support modifying image id when upgrading.
  main.go
  pkg/upgrade/base.go
  pkg/upgrade/config.go
  pkg/upgrade/control_plane.go
  pkg/upgrade/machine_deployment.go
  pkg/upgrade/machine_image.go
  pkg/upgrade/machine_image_test.go
Labels: cla-not-required, enhancement, p0

#29 restructure config
  main.go
  pkg/upgrade/base.go
  pkg/upgrade/config.go
  pkg/upgrade/config_test.go
Labels: cla-not-required

#31 Ensure errors have stack info
  pkg/internal/kubernetes/pod_exec.go
  pkg/internal/kubernetes/rest_config.go
  pkg/upgrade/config.go
  pkg/upgrade/control_plane.go
Labels: cla-not-required, enhancement, p2

#33 Adds the Kubeconfig Secret CLI flag
  main.go
Labels: cla-not-required

#34 Print a stack trace for errors
  main.go
Labels: cla-not-required, enhancement

#32 Secret lookup
  pkg/upgrade/base.go
  pkg/upgrade/key_pair.go
  pkg/upgrade/key_pair_test.go
Labels: cla-not-required

#39 Minor fixes
  main.go
  pkg/upgrade/control_plane.go
Labels: cla-not-required

#45 Switch to etcdctl v3
  pkg/upgrade/control_plane.go
  pkg/upgrade/control_plane_test.go
Labels: cla-not-required

#44 setup a test for multicp upgrade
  main_test.go
Labels: cla-not-required

#42 Adds upgrade ID flag and writes annotations to upgraded nodes
  main.go
  pkg/upgrade/base.go
  pkg/upgrade/config.go
  pkg/upgrade/control_plane.go
Labels: cla-not-required

#47 Extract an object responsible for creating machines
  Gopkg.lock
  pkg/upgrade/control_plane.go
  pkg/upgrade/machine_creator.go
  pkg/upgrade/machine_creator_test.go
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/config.go
  vendor/github.com/davecgh/go-spew/spew/doc.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/spew.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
Labels: cla-not-required
