Repository vmware/cluster-api-upgrade-tool, pull requests merged in 2019-07, with the labels that each got.

#54 Fix kubeconfig secret key name
  pkg/upgrade/key_pair.go
Labels: bug, cla-not-required, p0

#55 Do a nil check on log name
  pkg/logging/logrus_logr.go
Labels: cla-not-required

#53 Support upgrading etcd 3.2 / Kube 1.13
  pkg/upgrade/control_plane.go
  pkg/upgrade/control_plane_test.go
Labels: bug, cla-not-required, p0

#57 Edit kubeadm ConfigMap for control plane upgrades
  main.go
  pkg/upgrade/base.go
  pkg/upgrade/control_plane.go
  pkg/upgrade/control_plane_test.go
Labels: bug, cla-not-required, p0

#60 Correct example in readme
  README.md
Labels: cla-not-required, documentation

#62 Use Clusterctl's provider ID parsing
  Gopkg.lock
  Gopkg.toml
  pkg/internal/kubernetes/provider_id.go
  pkg/upgrade/base.go
  pkg/upgrade/control_plane.go
  pkg/upgrade/machine_creator.go
  vendor/k8s.io/apimachinery/pkg/api/errors/errors.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/codec.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
  vendor/sigs.k8s.io/cluster-api/logos/LICENSE.md
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineclass_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/scheme/doc.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/scheme/register.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/cluster.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/cluster_client.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/doc.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/generated_expansion.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machine.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machineclass.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machinedeployment.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machineset.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/noderefutil/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/noderefutil/providerid.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/noderefutil/util.go
Labels: cla-not-required
